Repository factory24/contributing-guide, pull requests merged in 2019-09, with the labels that each got.

#2 Add & Update: How To Contribute Guide
  How_to_Contribute.md
Labels: enhancement

#3 Modify Syntax Hightlights
  How_to_Contribute.md
Labels: enhancement

#5 Add: Factory24 code of conduct
  Code_Of_Conduct.md
Labels: enhancement

#6 Update COC pledge
  Code_Of_Conduct.md
Labels: enhancement

#7 Update: How To Contribute guideline
  How_to_Contribute.md
Labels: enhancement

#8 Modify: COC standards listings
  Code_Of_Conduct.md
Labels: enhancement

#10 finalize README update
  README.md
Labels: documentation

#13 Initial Commit: Add Maintainers Best Practices
  Code_Of_Conduct.md
  Maintainers_Best_Practices.md
Labels: documentation, enhancement

#14 Add: MBP Introduction
  Maintainers_Best_Practices.md
Labels: documentation, enhancement

#15 Add: Maintainers SelfCare Tips
  Maintainers_Best_Practices.md
Labels: documentation, enhancement
